### ISSUE TITLE
At "make destroy" I encounter the error "Command 'make' not found..."

### ISSUE THREAD

**Issue by Dez-BlueRose** [fhsinchy/the-docker-handbook#10]
If user (like myself) doesn't install the Visual Studio Code, the "make destroy" step fails due to make not being present on the system.  WSL2 Ubuntu reports:
```
Command 'make' not found, but can be installed with:

sudo apt install make        # version 4.2.1-1.2, or
sudo apt install make-guile  # version 4.2.1-1.2

```

CMD reports:
```'make' is not recognized as an internal or external command,
operable program or batch file.
```

I addressed in WSL2 Ubuntu by simply running 
```sudo apt -y install make```
and since I - as you - prefer that shell to CMD, I only checked there to see if I happened to have a make utility installed on the legacy side of the system.

**Comment by fhsinchy** [comment]
Thanks a lot for pointing that out to me. I completely forgot to mention `make` installation here. I'll update this part as soon as I can.

**Comment by fhsinchy** [comment]
Hey @Dez-BlueRose, thanks a lot for the suggestion. I was in the process of moving all my books out of GitBook and turn them into Hugo generated static sites. I've finished that and soon will start working on updating the Docker Handbook. Likewise, I'll make sure to take into account all your suggestions. Again, thanks a lot for the patient.
