### ISSUE TITLE
I cannot create a note?

### ISSUE THREAD

**Issue by Dez-BlueRose** [fhsinchy/the-docker-handbook#14]
Followed through the final steps, and while my Notes front-end came up as expected and shown in your example, I wasn't able to create a note.  Clicked "Create", and got to the create interface, entered text in the title and contents boxes, clicked the "Save" button and nothing happened.   Don't know nearly enough about the solution to have a good idea if this is something broken on my end or something that might be in the sources.

Thanks again for a great intro to Docker!

**Comment by fhsinchy** [comment]
Can you provide me with a screenshot of your browser console please?

**Comment by Dez-BlueRose** [comment]
:D Well, I went to do that, and am no longer able to replicate the failure.  Successfully created multiple new notes. Not sure what went wrong before, but I'm going to chalk this up to user error and flag this closed. :-)

**Comment by fhsinchy** [comment]
I'm hapoy to rear that mate. Let me know if you get to reproduce it.
