### ISSUE TITLE
Passing commands to a container with pipes

### ISSUE THREAD

**Issue by ngleb** [fhsinchy/the-docker-handbook#19]
Hello!

In the section "Container Manipulation Basics" → "How to Execute Commands Inside a Container", there's the following statement:

> What happens here is that, in a container run command, whatever you pass after the image name gets passed to the default entry point of the image.

and the command is this one:
```
docker container run --rm busybox echo -n my-secret | base64
```
I think this is not entirely true in this example because `| base 64` is not passed to the container but is executed on a host system. This might not be obvious for some people (and it was not obvious for me tbh).

**Comment by fhsinchy** [comment]
Hmmm. That flew under my radar. What you're saying makes a lot more sense. I'll correct it this weekend hopefully.

Thanks a lot for pointing it out mate.

**Comment by drachenminister** [comment]
Stumbled across the same thing today. Found that the following would work though:

`docker container run --rm busybox sh -c "echo -n my-secret | base64"`

**Comment by fhsinchy** [comment]
I've updated the book. Thanks a lot for your contributions @drachenminister and @ngleb
