### ISSUE TITLE
Missing libssl1.1 package when building nginx from sources

### ISSUE THREAD

**Issue by ngleb** [fhsinchy/the-docker-handbook#20]
Hello!

In section ["Image manipulation basics" →"Optimizing images"](https://docker.farhan.info/image-manipulation-basics#understanding-the-many-layers-of-an-image), Dockerfile needs to be updated to minimize the image. However `libssl1.1` library also gets removed and nginx won't start. In the example, Dockerfile uses `ubuntu:latest` which is currently uses Ubuntu 20.04.2 aka Focal Fossa. `libssl1.1` package is not installed by default in this image, it seems that it gets pulled as a dependency when you install packages to build nginx, but then it gets removed.

The output is the following:
```
$ docker logs custom-nginx 
nginx: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I think Dockerfile needs an additional line that installs `libssl1.1`.

```
FROM ubuntu:latest

EXPOSE 80

ARG FILENAME="nginx-1.19.8"
ARG EXTENSION="tar.gz"

ADD https://nginx.org/download/${FILENAME}.${EXTENSION} .

RUN apt-get update && \
    apt-get install -y build-essential \
                       libpcre3 \
                       libpcre3-dev \
                       zlib1g \
                       zlib1g-dev \
                       libssl1.1 \
                       libssl-dev && \
    tar -xvf ${FILENAME}.${EXTENSION} && rm ${FILENAME}.${EXTENSION} && \
    cd ${FILENAME} && \
    ./configure \
        --sbin-path=/usr/bin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --with-pcre \
        --pid-path=/var/run/nginx.pid \
        --with-http_ssl_module && \
    make -j8 && make install && \
    cd / && rm -rfv /${FILENAME} && \
    apt-get remove -y build-essential \
                      libpcre3-dev \
                      zlib1g-dev \
                      libssl-dev && \
    apt-get autoremove -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["nginx", "-g", "daemon off;"]
```

BTW, users are not adviced to always test their images, which is not good.

**Comment by fhsinchy** [comment]
Hmmm. I thought I removed that line!! This too wilk be fixed mate. Thanks a bunch for pointing that out. And yes I'll increase the number of tests ans will recommend readers to test. Thanks again mate.

**Comment by fhsinchy** [comment]
Hi @ngleb I've tested this code and seems to work just fine in my home and office machines. I'm not sure why it isn't working in your case. The `libssl-dev` package is not a runtime pre-requisite but `libssl1.1` is which gets pulled in on line during the first `RUN` instruction. I'm closing this issue and will look into the other issue you created.

Thanks a lot for contributing mate.

**Comment by ngleb** [comment]
I'm not sure which version you've tested, but the code from my comment is working and the example from the book is not working.

`libssl1.1` is pulled in as a dependency when `libssl-dev` is installed.
Then `libssl-dev` is removed with `apt-get remove -y libssl-dev`
Then `libssl1.1` is removed with `apt-get auroremove`

It can be reproduced with a clean ubuntu:latest conainer:

```
root@60c14780f96a:/# apt-get remove libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libssl1.1
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  libssl-dev
0 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
After this operation, 8006 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 4250 files and directories currently installed.)
Removing libssl-dev:amd64 (1.1.1f-1ubuntu2.3) ...
root@60c14780f96a:/# apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libssl1.1
0 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
After this operation, 4123 kB disk space will be freed.
Do you want to continue? [Y/n] 
```

**Comment by fhsinchy** [comment]
Aha! Again my bad my bad. I was testing the FCC version https://www.freecodecamp.org/news/the-docker-handbook/#how-to-optimize-docker-images

I've just updated the gitbook version with your fix as well. So it should be functional everywhere now.

**Comment by ngleb** [comment]
Yes, I was using the example from Gitbook. At first I was reading FCC version but then switched to Gitbook version because its navigation is a bit easier. It has a table of contents for all book on the sidebar and for each chapter, so it's easier to follow.
