### ISSUE TITLE
Add PDF Version

### ISSUE THREAD

**Issue by kartva** [fhsinchy/the-docker-handbook#24]
Currently, trying to print the FreeCodeCamp or GitBook version results in 141 and 4 pages resp.

It is messy.
Found [this guide](https://docs.gitbook.com/features/pdf-export) for gitbook for PDF export, but I'm unsure of the process, having never used it myself.

**Comment by fhsinchy** [comment]
Hi @DesmondWillowbrook, thanks a lot for the suggestion. I was in the process of moving all my books out of GitBook and turn them into Hugo generated static sites. I'll soon add PDF versions of the book to this repo. I'm still writing the tool necessary for generating the PDF copy.
