### ISSUE TITLE
Windows Security Alert on attempt to start notes-api container

### ISSUE THREAD

**Issue by Dez-BlueRose** [fhsinchy/the-docker-handbook#9]
Working through the documentation (including new installation of Docker Desktop on Windows 10 which already had WSL2 installed and operational), Windows Defender Firewall popped up with a "Windows Security Alert" dialog box:

![image](https://user-images.githubusercontent.com/5853752/107141086-577f0200-68db-11eb-9ce5-5aa1e4041b72.png)

Should we update the document to address this? (The container example appears to be working fine in my situation, even though I "Cancel"ed the dialog box.)

**Comment by fhsinchy** [comment]
I thought Windows users are well aware of this alert so I didn't mention this. But Thanks for this screenshot, I may add it later.

**Comment by Dez-BlueRose** [comment]
It's common enough, but due to its potential security implications for the user, thought it might be worth mentioning.

**Comment by fhsinchy** [comment]
> It's common enough, but due to its potential security implications for the user, thought it might be worth mentioning.

It is worth mentioning mate. Thanks a lot again for you awesome contributions. I appreciate it.

**Comment by Dez-BlueRose** [comment]
Happy to help. Thanks for writing and sharing such a great resource for those of us wanting to wrap our heads around Docker, and needing a good place to start!

**Comment by fhsinchy** [comment]
Hoping to do a lot more mate. Afterall, sharing is caring.
